version: "3.2"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - .:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app-net
  php:
    container_name: php
    build:
      context: .
    volumes:
      - .:/var/www/html/
      - ./var/csv:/var/www/html/var/csv
      - ./messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
    ports:
      - "80:80"
    networks:
      - app-net
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=docker
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - "5672:5672"
    networks:
      - app-net

networks:
  app-net:

